s_joe_juneau		     01 05
s_guy_hebert		     01 07
s_radek_bonk		     01 09
s_ulf_dahlen		     01 12
s_kelly_hrudey		     01 13
s_jeremy_roenick	     01 17
s_derek_plante		     01 17
s_mark_messier		     01 18
s_sylvain_cote		     01 19
s_brian_bradley		     01 21
s_doug_weight		     01 21
s_brendan_shanahan	     01 23
s_chris_chelios		     01 25
s_esa_tikkanen		     01 25
s_wayne_gretzky		     01 26
s_dominik_hasek		     01 29
s_sean_burke		     01 29
s_mark_recchi		     02 01
s_geoff_sanderson	     02 01
s_arturs_irbe		     02 02
s_denis_savard		     02 04
s_peter_bondra		     02 07
s_alexandre_daigle	     02 07
s_kirk_muller		     02 08
s_dino_ciccarelli	     02 08
s_derek_king		     02 11
s_mats_sundin		     02 13
s_jaromir_jagr		     02 15
s_tim_chevaldae		     02 15
s_luc_robitaille	     02 17
s_alexander_mogilny	     02 18
s_andy_moog		     02 18
s_pat_lafontaine	     02 22
s_bernie_nicholls	     02 24
s_mike_vernon		     02 24
s_eric_lindros		     02 28
s_brian_leetch		     03 03
s_phil_housley		     03 09
s_gord_murphy		     03 23
s_darren_puppa		     03 23
s_ken_wregget		     03 25
s_keith_tkachuk		     03 28
s_trevor_kidd		     03 29
s_pavel_bure		     03 31
s_scott_stevens		     04 01
s_dale_hawerchuk	     04 04
s_rick_tocchet		     04 09
s_trevor_linden		     04 11
s_roman_hamrlik		     04 12
s_ed_belfour		     04 21
s_curtis_joseph		     04 29
s_ron_hextall		     05 03
s_mikael_renberg	     05 05
s_martin_brodeur	     05 06
s_steve_yzerman		     05 09
s_jari_kurri		     05 18
s_jim_carey		     05 31
s_paul_coffey		     06 01
s_cam_neely		     06 06
s_stephane_richer	     06 07
s_mike_modano		     06 07
s_scott_mellanby	     06 11
s_eric_desjardins	     06 14
s_jesse_belanger	     06 15
s_stephane_fiset	     06 17
s_doug_bodger		     06 18
s_sergei_makarov	     06 19
s_felix_potvin		     06 23
s_doug_gilmour		     06 25
s_robert_reichel	     06 25
s_kirk_mclean		     06 26
s_theoren_fleury	     06 29
s_jamie_mclennan	     06 30
s_teemu_selanne		     07 03
s_joe_sakic		     07 07
s_steve_thomas		     07 15
s_claude_lemieux	     07 16
s_andrew_cassels	     07 23
s_sandis_ozolinsh	     08 03
s_rod_brindamour	     08 09 
s_brett_hull		     08 09
s_shayne_corson		     08 13
s_ray_ferraro		     08 23
s_adam_oates		     08 27
s_pierre_turgeon	     08 29
s_john_vanbiesbrouck	     09 04
s_blaine_lacher		     09 05
s_kevin_hatcher		     09 09
s_joe_nieuwendyk	     09 10
s_igor_kravchuk		     09 13
s_tom_kurvers		     09 14
s_don_beaupre		     09 19
s_mike_richter		     09 22
s_owen_nolan		     09 22
s_dave_andreychuk	     09 29
s_alexei_zhamnov	     10 01
s_patrick_roy		     10 05
s_mario_lemieux		     10 05
s_jason_arnott		     10 11
s_paul_kariya		     10 16
s_wendel_clark		     10 25
s_alexei_yashin		     11 05
s_john_maclean		     11 20
s_petr_nedved		     12 09
s_dave_gagner		     12 11
s_sergei_fedorov	     12 13
s_bill_ranford		     12 14
s_vincent_damphousse	     12 17
s_bob_corkum		     12 18
s_petr_klima		     12 23
s_ray_bourque		     12 28
s_sheridan_oursler	     01-03  sno		104_100
s_jack_h_haeger		     01-06  jah		 80_68
s_mike_waldron		     01-09  mjw		100_100
s_mike_ossian		     01-11  ott		 98_96
s_mark_penacho		     01-13  mdp		100_98
s_jim_gentile		     01-23  jpg		100_100
s_eugene_jarvis		     01-27  epj		 98_101
s_sal_divita		     02-01  sal		102_97
s_ed_boon		     02-22  ejb		100_100
s_jake_simpson		     02-22  jms		 98_100
s_jennifer_fedesna	     02-25  jkf		 80_68
s_mike_lynch		     02-28  mjl		100_100
s_mark_turmell		     03-22  mjt		100_106
s_ray_macika		     03-26  rem		 98_102
s_ed_keenan		     04-10  ejk		102_100
s_pat_cox		     04-11  pgc		 98_104
s_ross_shaffer		     04-13  frs		100_104
s_luis_mangubat		     04-18  lm 		 98_96
s_matt_booty		     04-18  mvb		100_104
s_brian_eddie		     04-20  bre		 96_98
s_jennifer_hedrick	     05-03  jjh		 97_96
s_bridgitte_fedesna	     05-09  bmf		 96_96
s_chris_bobrowski	     05-12  me 		100_98
s_jim_rohn		     05-22  jr 		102_97
s_mark_loffredo		     05-25  ml 		104_98
s_dave_zabloudil	     05-28  zab		 98_98
s_ken_williams		     05-30  wkw		100_102
s_jim_greene		     05-31  jdg		102_102
s_eddie_ferrier		     06-10  ef 		100_96
s_glenn_shipp		     06-11  gws		100_100
s_john_newcomer		     06-18  jrn		104_106
s_cary_mednick		     07-02  cmm		 96_98
s_maryann_rohn		     07-07  mac		 96_96
s_christa_woss		     07-09  clw		 96_96
s_jack_haeger		     07-13  jeh		100_98
s_joan_faux		     07-17  jbf		 96_96
s_tony_metke		     07-19  arm		100_100
s_jason_skiles		     07-29  jms		102_100
s_john_carlton		     08-05  jmc		 98_96
s_dave_michicich	     08-06  dlm		102_102
s_martin_martinez	     08-07  mam		102_96
s_xion_cooper		     08-09  xc 		100_98
s_ray_gay		     08-11  rmg		 98_96
s_warren_davis		     08-17  wbd		100_102
s_matt_davis		     08-19  mjd		 98_102
s_john_tobias		     08-24  tob		 98_96
s_steve_beran		     08-29  sab		 98_100
s_al_lasko		     08-31  al 		 82_90
s_steve_correll		     09-16  rsc		 98_96
s_jon_hey		     09-20  jwh		100_100
s_ted_valvanis		     10-03  tv 		100_100
s_george_petro		     10-08  gnp		 98_98
s_mike_vinikour		     10-14  mxv		 98_100
s_jim_tianis		     10-20  djt		102_100
s_art_tianis		     10-23  ajt		104_100
s_john_lowes		     11-04  jml		 98_100
s_eugene_geer		     11-05  oeg		104_100
s_carlos_pesina		     11-15  ccp		102_102
s_nik_ehrlik		     11-17  nik		 98_98
s_andy_lycke		     11-23  al 		100_98
s_josh_tsui		     11-28  cet		 98_96
s_ted_barber		     12-05  bar		100_100
s_tony_goskie		     12-07  twg		102_102
s_paul_dussault		     12-17  pgd		100_100
s_bill_dabelstein	     12-31  doz		 96_106

s_jon_casey		     03-29










80,68
82,90
96,96
96,98
96,106
97,96
98,101
100,98
100,106
102,96
102,97
102,100
102,102
104,106
