#include <stdio.h>

double d1,h;
int ccount;

void main();
void intro();
void zscales();
void zscale(int s1, int s2);
void xscale();
void zybase();
void fws();
void invscale();
void outhword(int num);
void outhlong(int num1,int num2);
void outword(int num);
double z_scale(double z, int s);
double x_scale(double z);
double y_base(double z);
double z_from_y(double y);
double invsc(double y);

void main() {
	d1 = 1379;
	h = 579;
	intro();
	zscales();
	zybase();
	xscale();
	fws();
	invscale();
}

void intro() {
	printf("\t.FILE\t\t\"HHTABLES.ASM\"\n");
	printf("\t.WIDTH\t132\n");
	printf("\t.OPTION	B,D,L,T\n");
	printf("\t.MNOLIST\n");
	printf(";\tthis file generated by TABLES.C\n");
	printf("\t.include\t\"hhtables.e\"\n");
	printf("\n");
	printf("; end of include files\n");
	printf("\n");
	printf("\t.text\n");
	printf("\t.even\n");
	printf("\n");
	printf("xzy_offset\tequ	9400*16\t\t;distance between tables\n");
}

void zscales() {
	int s1,s2;
	zscale(94,100);
	zscale(95,92);
	zscale(95,99);
	zscale(97,97);
	zscale(97,103);
	zscale(98,97);
	zscale(98,100);
	zscale(98,103);
	zscale(98,106);
	zscale(100,97);
	zscale(100,100);
	zscale(101,103);
	zscale(103,97);
	zscale(104,101);
	zscale(104,103);
	zscale(106,99);
	zscale(107,103);
	zscale(108,106);
	zscale(119,119);			//goalie 100,100 scale
	zscale(50,50);

	zscale(25,25);
}

void zscale(int s1, int s2) {
	double z;
	ccount = 0;
	printf ("\n");
	for (z = -100; z < 0; z++)
		outhlong((int)z_scale(z,s1),(int)z_scale(z,s2));
	printf("\nzscale_%d_%d_table\n",s1,s2);
	ccount = 0;
	for (z = 0; z < 2000; z++)
		outhlong((int)z_scale(z,s1),(int)z_scale(z,s2));
}

void xscale(){
	double z;
	printf("\n");
	ccount = 0;
	printf ("\n");
	for (z = -100; z < 2250; z++)
		outhword((int)x_scale(z));
	for (z = -100; z < 0; z++)
		outhword((int)x_scale(z));
	printf("\nxscale_table\n");
	ccount = 0;
	for (z = 0; z < 2250; z++)
		outhword((int)x_scale(z));
	for (z = -100; z < 2250; z++)
		outhword((int)x_scale(z));
	for (z = -100; z < 2250; z++)
		outhword((int)x_scale(z));
}

void zybase(){
	double z;
	printf("\n");
	ccount = 0;
	printf ("\n");
	for (z = -100; z < 2250; z++)
		outword((int)y_base(z));
	for (z = -100; z < 0; z++)
		outword((int)y_base(z));
	printf("\nzybase_table\n");
	ccount = 0;
	for (z = 0; z < 2250; z++)
		outword((int)y_base(z));
	for (z = -100; z < 2250; z++)
		outword((int)y_base(z));
	for (z = -100; z < 2250; z++)
		outword((int)y_base(z));
}

void fws() {
	double y;
	printf("\n");
	ccount = 0;
	printf("\n");
	for (y = -300; y < 0; y++)
		outword((int)z_from_y(y));
	printf ("\nfws_table\n");
	ccount = 0;
	for (y = 0; y < 50; y++)
		outword((int)z_from_y(y));
}

void invscale() {
	double y;
	printf("\n");
	printf ("\ninvscale_table\n");
	ccount = 0;
	outword(32767);
	outword(32767);
	outword(32767);
	for (y = 3; y < 1100; y++)
		outword((int)invsc(y));
}

void outword(int num) {
	if (ccount)
		printf(",%d",num);
	else
		printf("\t.word\t%d",num);
	if (++ccount == 16) {
		printf("\n");
		ccount = 0;
	}
}

void outhword(int num) {
	if (ccount)
		printf(",0%04xh",num);
	else
		printf("\t.word\t0%04xh",num);
	if (++ccount == 16) {
		printf("\n");
		ccount = 0;
	}
}

void outhlong(int num1, int num2) {
	if (ccount)
		printf(",[0%04xh,0%04xh]",num2,num1);
	else
		printf("\t.long\t[0%04xh,0%04xh]",num2,num1);
	if (++ccount == 8) {
		printf("\n");
		ccount = 0;
	}
}

double z_scale(double z, int s) {
	return (d1 + z) / d1 * 256 / ((double)s / 100);
}

double x_scale(double z) {
	return (d1 / (d1 + z) * 0x4000);
}

double y_base(double z) {
	return ((z * h) / (d1 + z));
}

double z_from_y(double y) {
	return ((-d1 * y) / (y + h));
}

double invsc(double y) {
	return (65536 / y);
}
