;
;	GLOBALS DEFINED IN HHADJ.ASM
;
;	ROUTINES:
;
	.def		GET_CSPT
	.def		CS_POINT        
	.def		TAMPEREDP
	.def		DO_ADJH
	.def		GO_PADJ         
	.def		GO_GADJ         
	.def		USA_ELECTITLE
	.def		USA_10   
	.def		USA_9   
	.def		USA_4
	.def		USA_3
	.def		USA_2
	.def		USA_1
	.def		BINBCD
	.def		GERMAN_ELECTITLE
	.def		GERMAN_5        
	.def		GERMAN_4
	.def		GERMAN_3
	.def		GERMAN_2
	.def		GERMAN_1
	.def		FRENCH_ELECTITLE
	.def		FRENCH_12       
	.def		FRENCH_11       
	.def		FRENCH_4
	.def		FRENCH_3
	.def		FRENCH_2
	.def		FRENCH_1
	.def		CKDIP
	.def		MEN_GADJ        
	.def		MEN_PADJ        
	.def		SET_COIN_ADJ
	.def		DIPCOINTAB
;
;	RAM:
;
