;
;	GLOBALS DEFINED IN HHADJ.ASM
;
;	ROUTINES:
;
	.global		GET_CSPT
	.global		CS_POINT        ; WBD
	.global		TAMPEREDP
	.global		DO_ADJH
	.global		GO_GADJ ; WBD
	.global		GO_PADJ ; WBD
	.global		USA_ELECTITLE
	.global		USA_10   ; WBD
	.global		USA_9   ; WBD
	.global		USA_4
	.global		USA_3
	.global		USA_2
	.global		USA_1
	.global		BINBCD
	.global		GERMAN_ELECTITLE
	.global		GERMAN_5        ; WBD
	.global		GERMAN_4
	.global		GERMAN_3
	.global		GERMAN_2
	.global		GERMAN_1
	.global		FRENCH_ELECTITLE
	.global		FRENCH_12       ; WBD
	.global		FRENCH_11       ; WBD
	.global		FRENCH_4
	.global		FRENCH_3
	.global		FRENCH_2
	.global		FRENCH_1
	.global		DIPCREDTAB
	.global		CKDIP
	.global		MEN_GADJ         ; WBD
	.global		MEN_PADJ         ; WBD
	.global		SET_COIN_ADJ
	.global		DIPCOINTAB
;
;	RAM:
;
