;
;	GLOBALS DEFINED IN HHAFUNC.ASM
;
;	ROUTINES:
;
	.global		A_SET_OXZVEL
	.global		A_CLR_OXZVEL
	.global		A_2FUNCS
	.global		A_3FUNCS
	.global		A_4FUNCS
	.global		A_5FUNCS
	.global		A_RAND_ANIMSLP
	.global		A_RAND_BRANCH
	.global		A_Anim_DSJ
	.global		A_SET_ANIMLOOP
	.global		A_RAND_JUMP
	.global		A_RAND_REL_BYTE
	.global		A_SET_OYVEL
	.global		A_SET_OXVEL
	.global		A_DO_SOUND
;
;	RAM:
;

