;
;	GLOBALS DEFINED IN HHATTRCT.ASM
;
;	ROUTINES:
;
	.global		ATTRACT_MODE
	.global		in_at_game
	.global		stop_attract_game_quick
	.global		CREDIT_PAGE_JUMPS
	.global		ATT_MODE_TOPTEN
	.global		stop_attract_game_quick_SNDOK
	.global		build_random_hint
	.global		amode_starting_point
	.global		congratulations_page
	.global		sound_store_fp
	.global		sound_store_c2
	.global		sound_store_c1
	.global		sound_store_t1
	.global		stop_all_objects
;
;	RAM:
;

