;
;	GLOBALS DEFINED IN HHATTRCT.ASM
;
;	ROUTINES:
;
	.def		ATTRACT_MODE
	.def		in_at_game
	.def		stop_attract_game_quick
	.def		CREDIT_PAGE_JUMPS
	.def		ATT_MODE_TOPTEN
	.def		stop_attract_game_quick_SNDOK
	.def		build_random_hint
	.def		amode_starting_point
	.def		congratulations_page
	.def		sound_store_fp
	.def		sound_store_c2
	.def		sound_store_c1
	.def		sound_store_t1
	.def		stop_all_objects
;
;	RAM:
;

