;
;	GLOBALS DEFINED IN HHPALL.ASM
;
;	ROUTINES:
;
	.def		INIT_PAL
	.def		PALSET
	.def		GETFPAL
	.def		FINDPAL
	.def		CLRFPAL
	.def		PALTRANS
	.def		FREEPAL
	.def		DELETE_PAL
	.def		DELPAL
	.def		CLRPAL
	.def		CLR_0PALS
	.def		INC_PALCNT
	.def		GET_PALID
	.def		CHANGE_PAL
	.def		CHANGE_PAL_MULTI
	.def		A_CHANGE_PAL
	.def		FREEPALCNT
	.def		BLACKPAL
	.def		MAX_PALXFERS
	.def		RESET_MAX_PALXFERS
	.def		build_whitepal
	.def		WHITE_FLAG
;
;	RAM:
;

