;
;	GLOBALS DEFINED IN HHPIC.ASM
;
;	ROUTINES:
;
	.global		go_hardware
	.global		mess_hardware
	.global		hardware_help
	.global		copy_string
	.global		dec_to_asc
	.global		_serial_number
	.global		_man_date
	.global		message_buffer
	.global		_read_pic_data
	.global		InitPIC
	.global		copy_rom_string
	.global		concat_string
	.global		octopus_button
	.global		octopus_count
	.global		message_buffer2
;
;	RAM:
;
