;
;	GLOBALS DEFINED IN HHRSCR.ASM
;
;	ROUTINES:
;
	.global		set_ref_setup_script
	.global		set_ref_drop_script
	.global		set_ref_skate_back_script
	.global		set_ref_bump_script
	.global		ref_size
	.global		set_ref_stand_script
	.global		set_ref_skate_right_script
	.global		set_ref_skate_left_script
	.global		set_ref_look_script
	.global		set_ref_skate_right_norm_script
	.global		set_ref_skate_left_norm_script
	.global		set_ref_stop_left_right_script
;
;	RAM:
;

