;
;	GLOBALS DEFINED IN HHSELECT.ASM
;
;	ROUTINES:
;
	.def		create_players
	.def		drone_to_goalie
	.def		goalie_to_drone
	.def		reset_all_pulled_goalies
	.def		player_4_turbopal
	.def		player_3_turbopal
	.def		player_2_turbopal
	.def		player_1_turbopal
	.def		replace_all_turbo_palettes
	.def		find_special_character
	.def		COPY_HEAD_PALS
	.def		ALLOCATE_ALT_HEAD_PALS
	.def		DEALLOCATE_ALT_HEAD_PALS
	.def		player_1_headpal_alt
	.def		team_1_vidpal
;
;	RAM:
;

