;
;	GLOBALS DEFINED IN HHSTABL2.ASM
;
;	ROUTINES:
;
	.global		player_data
	.global		CHELIOS1
	.global		M_CHELIOS
	.global		pspeed_data_powered
	.global		pass_data_powered
	.global		shoot_data_powered
	.global		player_speed_data
	.global		player_stop_data
	.global		player_corner_data
	.global		player_shoot_data
	.global		player_pass_data
	.global		player_face_data
	.global		player_handle_data
	.global		player_check_data
;
;	RAM:
;

