;
;	GLOBALS DEFINED IN HHSTABL2.ASM
;
;	ROUTINES:
;
	.def		player_data
	.def		CHELIOS1
	.def		M_CHELIOS
	.def		pspeed_data_powered
	.def		pass_data_powered
	.def		shoot_data_powered
	.def		player_speed_data
	.def		player_stop_data
	.def		player_corner_data
	.def		player_shoot_data
	.def		player_pass_data
	.def		player_face_data
	.def		player_handle_data
	.def		player_check_data
;
;	RAM:
;

