;
;	GLOBALS DEFINED IN HHTIMER.ASM
;
;	ROUTINES:
;
	.def		stop_timer
	.def		game_timer
	.def		init_timer_value
	.def		start_timer
	.def		minutes
	.def		tenseconds
	.def		seconds
	.def		tenths
	.def		timer_ok
	.def		timer_on
	.def		npal_0
	.def		rinkpallist
	.def		rpallist
	.def		show_timer
	.def		show_at_least_timer
	.def		init_timer_dma
	.def		clean_fill_scores
	.def		flash_team_who_scored
	.def		npal_109
	.def		T2BP
;
;	RAM:
;

