;
;	GLOBALS DEFINED IN HHUTIL.ASM
;
;	ROUTINES:
;
	.def		SCRCLR
	.def		MYOINIT
	.def		DMAQWAIT
	.def		RANDOM
	.def		SETPPROC
	.def		CLEAR_PAGE2
	.def		CLEAR_PAGE3
	.def		CLR_SCRN
	.def		RANGERND
	.def		CLRBLOCK
	.def		RANDPER
	.def		FILLAREA
	.def		BLNKAREA
	.def		DRAWBOX_OBJ
	.def		DMAWAIT
	.def		RANDU
	.def		SLINEVEL
	.def		T2FIXED
	.def		RAND0
	.def		SRAND
	.def		RANGRAND
;
;	RAM:
;

