;
;	GLOBALS DEFINED IN HHUTIL.ASM
;
;	ROUTINES:
;
	.global		SCRCLR
	.global		MYOINIT
	.global		DMAQWAIT
	.global		RANDOM
	.global		SETPPROC
	.global		CLEAR_PAGE2
	.global		CLEAR_PAGE3
	.global		CLR_SCRN
	.global		RANGERND
	.global		CLRBLOCK
	.global		RANDPER
	.global		FILLAREA
	.global		BLNKAREA
	.global		DRAWBOX_OBJ
	.global		DMAWAIT
	.global		RANDU
	.global		SLINEVEL
	.global		T2FIXED
	.global		RAND0
	.global		SRAND
	.global		RANGRAND
;
;	RAM:
;

