;
;	GLOBALS DEFINED IN HH.ASM
;
;	ROUTINES:
;
	.def		MAIN_INIT
	.def		MAIN_GO
	.def		SETUP
	.def		WIPEOUT
	.def		SWITCH_ESCAPE
	.def		ATSTRT
	.def		EXEC_LP
	.def		CLSCRACH
	.def		PCMOSRET
	.def		WARMSET
	.def		POWERRET
	.def		GRAMINIT
	.def		IDATALEN
	.def		INITDATA
	.def		SWITCH_SPOKEN
	.def		IAUTOE
	.def		DIPINIT
	.def		DUMDIE
	.def		KILL_DESTRUCTIBLES
	.def		DUMRETS
	.def		POWERUP
;
;	RAM:
;

