;
;	GLOBALS DEFINED IN HH.ASM
;
;	ROUTINES:
;
	.global		MAIN_INIT
	.global		MAIN_GO
	.global		SETUP
	.global		WIPEOUT
	.global		SWITCH_ESCAPE
	.global		ATSTRT
	.global		EXEC_LP
	.global		CLSCRACH
	.global		PCMOSRET
	.global		WARMSET
	.global		POWERRET
	.global		GRAMINIT
	.global		IDATALEN
	.global		INITDATA
	.global		SWITCH_SPOKEN
	.global		IAUTOE
	.global		DIPINIT
	.global		DUMDIE
	.global		KILL_DESTRUCTIBLES
	.global		DUMRETS
	.global		POWERUP
;
;	RAM:
;

