;
;	GLOBALS DEFINED IN HHA.ASM
;
;	ROUTINES:
;
	.global		SW_4
	.global		SW_5
	.global		SW_6
	.global		SW_7
	.global		SW_12
	.global		SW_13
	.global		SW_14
	.global		SW_15
	.global		SW_20
	.global		SW_21
	.global		SW_22
	.global		SW_23
	.global		SW_28
	.global		SW_29
	.global		SW_30
	.global		SW_31
	.global		SW_34
	.global		SW_37
	.global		SW_41
	.global		SW_42
;
;	RAM:
;

