;
;	GLOBALS DEFINED IN HHGAME.ASM
;
;	ROUTINES:
;
	.global		player_start
	.global		check_for_player
	.global		fix_curplyrs
	.global		restart_game_mode
	.global		world_mt_point
	.global		team1_score
	.global		team2_score
	.global		team1
	.global		team2
	.global		team1_visitor
	.global		team2_visitor
	.global		game_over
	.global		period_over
	.global		period_start
	.global		period
;
;	RAM:
;

