;
;	GLOBALS DEFINED IN HHPALL.ASM
;
;	ROUTINES:
;
	.global		INIT_PAL
	.global		PALSET
	.global		GETFPAL
	.global		FINDPAL
	.global		CLRFPAL
	.global		PALTRANS
	.global		FREEPAL
	.global		DELETE_PAL
	.global		DELPAL
	.global		CLRPAL
	.global		CLR_0PALS
	.global		INC_PALCNT
	.global		GET_PALID
	.global		CHANGE_PAL
	.global		CHANGE_PAL_MULTI
	.global		A_CHANGE_PAL
	.global		FREEPALCNT
	.global		GET_SPARE_PAL
;
;	RAM:
;

