loadw HH                   /TC /FI /E /1 >  ERRLOAD
loadw F2                /A /TC /FI /E /1 >> ERRLOAD
loadw F5                /A /TC /FI /E /1 >> ERRLOAD
loadw F7                /A /TC /FI /E /1 >> ERRLOAD
loadw NOW3              /A /TC /FI /E /1 >> ERRLOAD
loadw HH2               /A /TC /FI /E /1 >> ERRLOAD
loadw F1                /A /TC /FI /E /1 >> ERRLOAD
loadw F3                /A /TC /FI /E /1 >> ERRLOAD
loadw F4                /A /TC /FI /E /1 >> ERRLOAD
loadw F6                /A /TC /FI /E /1 >> ERRLOAD
loadw F8                /A /TC /FI /E /1 >> ERRLOAD
loadw F9                /A /TC /FI /E /1 >> ERRLOAD
loadw HHGOAL2           /A /TC /FI /E /1 >> ERRLOAD
loadw HHHEADS3          /A /TC /FI /E /1 >> ERRLOAD
loadw SANS1             /A /TC /FI /E /1 >> ERRLOAD
loadw SANS2             /A /TC /FI /E /1 >> ERRLOAD
loadw MASK3             /A /TC /FI /E /1 >> ERRLOAD
del *.~bl
del l2temp
